# 1.Print 'Hello HCIA'.

In [3]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
print(1+2)

3


# 3.Define a list and replicate in three different ways.

In [1]:
a=[1,2,3]
print(a)
print(a[:])
print(*a)


[1, 2, 3]
[1, 2, 3]
1 2 3


# 4.Define two lists and merge them together.

In [1]:
a=[1,2]
b=[4,5]
merge=(a+b)
print(merge)

[1, 2, 4, 5]


# 5. Get the last element of the list and print it.

In [4]:
a=[1,2,3]
a[-1]

3

# 6.Define a tuple that contains only one element.

In [6]:
t=(1)

# 7.Define a three-line long string.

In [17]:
ss=('''
    Три очень милых феечки
    cидели на скамеечке
    И, съев по булке с маслицем,
    Успели так замаслиться,
    Что мыли этих феечек
    Из трех садовых леечек.''')
print(ss)


    Три очень милых феечки
    cидели на скамеечке
    И, съев по булке с маслицем,
    Успели так замаслиться,
    Что мыли этих феечек
    Из трех садовых леечек.


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [16]:
a=[1,2,3]
for i in a:
    print(i)

1
2
3


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [19]:
def Mul(a,b):
    return(a*b)
Mul(8,6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [27]:
import numpy as np
import scipy as sp
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [26]:
import numpy as np
import scipy as sp
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [25]:
import numpy as np
import scipy as sp
a=np.arange(15)
a.shape=(3,5)
print(np.arange(15))
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(3, 5)


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [47]:
import numpy as np 
import scipy as sp 
a=np.arange(6).reshape(3,2)
b=np.arange(6).reshape(2,3)
c=np.matmul(a,b)
print(c)

[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
